export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const SAVE_DELIVERY_PRICE = "SAVE_DELIVERY_PRICE";

export const REMOVE_ALL_CART_ITEMS = "REMOVE_ALL_CART_ITEMS"